import { Manrope } from "next/font/google";
import "./globals.css";
import AllProvider from "@/provider/AllProvider";


const manrope = Manrope({
  variable: "--font-manrope", 
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
});

export const metadata = {
  title: "Cresify",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AllProvider>
    
        <body className={`${manrope.variable} antialiased`}>
        {/* <Navbar /> */}
        {children}
        {/* <Footer /> */}
      </body>
      </AllProvider>
    </html>
  );
}
